# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class K8shark < Formula
  desc "Kubernetes cluster state capture and mock API replay tool"
  homepage "https://github.com/phenixblue/k8shark"
  version "0.1.0-rc.5"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/phenixblue/k8shark/releases/download/v0.1.0-rc.5/k8shark_0.1.0-rc.5_darwin_amd64.tar.gz"
      sha256 "2ffa544a5fc0cc21feabeb8f8fa9912fca6943269e10fc6376c02f8b861f833f"

      define_method(:install) do
        bin.install "kshrk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/phenixblue/k8shark/releases/download/v0.1.0-rc.5/k8shark_0.1.0-rc.5_darwin_arm64.tar.gz"
      sha256 "8b4f3817361643424cb58e256b7a44e8d7a60a2ab1ff74c1ddc4bfbcf641aeb8"

      define_method(:install) do
        bin.install "kshrk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/phenixblue/k8shark/releases/download/v0.1.0-rc.5/k8shark_0.1.0-rc.5_linux_amd64.tar.gz"
      sha256 "661664b80614b8eb5c77526a9a2817dc27d5a6f49dd84b0be9742246ae5cafac"
      define_method(:install) do
        bin.install "kshrk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/phenixblue/k8shark/releases/download/v0.1.0-rc.5/k8shark_0.1.0-rc.5_linux_arm64.tar.gz"
      sha256 "59fa0ee89597f11e6cecf55f107d6c521c69ca8db666faccb6bc1efb4dfa0ba7"
      define_method(:install) do
        bin.install "kshrk"
      end
    end
  end

  test do
    system "#{bin}/kshrk", "version"
  end
end
