# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class K8shark@rc < Formula
  desc "Kubernetes cluster state capture and mock API replay tool (prerelease channel)"
  homepage "https://github.com/phenixblue/k8shark"
  version "0.5.1-rc.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/phenixblue/k8shark/releases/download/v0.5.1-rc.2/k8shark_0.5.1-rc.2_darwin_amd64.tar.gz"
      sha256 "2c49681919b0befed896d73fbdbba9297973331e7e3fb53dcd079fa218ed6210"

      define_method(:install) do
        bin.install "kshrk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/phenixblue/k8shark/releases/download/v0.5.1-rc.2/k8shark_0.5.1-rc.2_darwin_arm64.tar.gz"
      sha256 "edd657aee32c390ed1a50975ca983b20cd3f7f4c169f7768b81879759d338d96"

      define_method(:install) do
        bin.install "kshrk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/phenixblue/k8shark/releases/download/v0.5.1-rc.2/k8shark_0.5.1-rc.2_linux_amd64.tar.gz"
      sha256 "1c9f95e9bd9900ba85f9966e6f85363fd254db90df33fe3ad514be29d4b116a4"
      define_method(:install) do
        bin.install "kshrk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/phenixblue/k8shark/releases/download/v0.5.1-rc.2/k8shark_0.5.1-rc.2_linux_arm64.tar.gz"
      sha256 "1b03270a29329c794cd5696630dc8d15c168d8d7af1c3aac6b38cccc6f508f37"
      define_method(:install) do
        bin.install "kshrk"
      end
    end
  end

  test do
    system "#{bin}/kshrk", "version"
  end
end
