# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class K8shark < Formula
  desc "Kubernetes cluster state capture and mock API replay tool"
  homepage "https://github.com/phenixblue/k8shark"
  version "0.5.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/phenixblue/k8shark/releases/download/v0.5.1/k8shark_0.5.1_darwin_amd64.tar.gz"
      sha256 "bb1fc8b9eafa11cd0bdd547fdb7e26651e9c3c1727534f9b0770bef51e5a317a"

      define_method(:install) do
        bin.install "kshrk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/phenixblue/k8shark/releases/download/v0.5.1/k8shark_0.5.1_darwin_arm64.tar.gz"
      sha256 "780261c661f37a46a8c01b6a73cf02e9e4ce17b0235e8c0da2fd0321b1be92d4"

      define_method(:install) do
        bin.install "kshrk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/phenixblue/k8shark/releases/download/v0.5.1/k8shark_0.5.1_linux_amd64.tar.gz"
      sha256 "82b21771f10b008de09277840980dc4020ebb0090eb0830ecd6359b9e592c0a4"
      define_method(:install) do
        bin.install "kshrk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/phenixblue/k8shark/releases/download/v0.5.1/k8shark_0.5.1_linux_arm64.tar.gz"
      sha256 "3d6111a116f7f3e043bd0c68ab59ecfc2b0a1e77d45651bfed3e8cd48f6aa072"
      define_method(:install) do
        bin.install "kshrk"
      end
    end
  end

  test do
    system "#{bin}/kshrk", "version"
  end
end
