# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kapture < Formula
  desc "KubeVirt best-practices scanner for production readiness, security, and availability checks"
  homepage "https://github.com/phenixblue/kapture"
  version "0.1.0-rc5"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/phenixblue/kapture/releases/download/v0.1.0-rc5/kapture_0.1.0-rc5_darwin_amd64.tar.gz"
      sha256 "7270043d6162749a86fc3c62bf00eae44310f61e9e969fa3937a1d9af942b6f1"

      define_method(:install) do
        bin.install "kapture"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/phenixblue/kapture/releases/download/v0.1.0-rc5/kapture_0.1.0-rc5_darwin_arm64.tar.gz"
      sha256 "70cbb17e54a84751ab35bf6ba10320482751d1fc846b3b4544e9c9c432bdcba1"

      define_method(:install) do
        bin.install "kapture"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/phenixblue/kapture/releases/download/v0.1.0-rc5/kapture_0.1.0-rc5_linux_amd64.tar.gz"
      sha256 "4efed6f7a14a9387919805717be42028755bfc75b98eb0892767f288bb4fb8dc"
      define_method(:install) do
        bin.install "kapture"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/phenixblue/kapture/releases/download/v0.1.0-rc5/kapture_0.1.0-rc5_linux_arm64.tar.gz"
      sha256 "032db4a8e350a70900282af34d645d035d10d0ef982e6928970abf326300e616"
      define_method(:install) do
        bin.install "kapture"
      end
    end
  end

  test do
    system "#{bin}/kapture", "version"
  end
end
