# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kvirtbp < Formula
  desc "KubeVirt best-practices scanner for production readiness, security, and availability checks"
  homepage "https://github.com/phenixblue/kvirtbp"
  version "0.1.0-rc2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/phenixblue/kvirtbp/releases/download/v0.1.0-rc2/kvirtbp_0.1.0-rc2_darwin_amd64.tar.gz"
      sha256 "2a5e0f8dca93372ff344c0bbc4a97856401563d6ba7ec77b07a2fca18902c53d"

      define_method(:install) do
        bin.install "kvirtbp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/phenixblue/kvirtbp/releases/download/v0.1.0-rc2/kvirtbp_0.1.0-rc2_darwin_arm64.tar.gz"
      sha256 "cb68b1b1e0dacea4c7ce699dfac9426201c070aed94c3c1f8cf4ee2e999a2a8c"

      define_method(:install) do
        bin.install "kvirtbp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/phenixblue/kvirtbp/releases/download/v0.1.0-rc2/kvirtbp_0.1.0-rc2_linux_amd64.tar.gz"
      sha256 "d7b5d691bf4823c10b041711f0c39cb45856e09b41947fe5205bfb05d26c846e"
      define_method(:install) do
        bin.install "kvirtbp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/phenixblue/kvirtbp/releases/download/v0.1.0-rc2/kvirtbp_0.1.0-rc2_linux_arm64.tar.gz"
      sha256 "0bedc63587043db39b9c4db7d1ba186a00ffddbe67c9ac75e1669f902e732d4a"
      define_method(:install) do
        bin.install "kvirtbp"
      end
    end
  end

  test do
    system "#{bin}/kvirtbp", "version"
  end
end
