# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kvirtbp < Formula
  desc "KubeVirt best-practices scanner for production readiness, security, and availability checks"
  homepage "https://github.com/phenixblue/kvirtbp"
  version "0.1.0-rc3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/phenixblue/kvirtbp/releases/download/v0.1.0-rc3/kvirtbp_0.1.0-rc3_darwin_amd64.tar.gz"
      sha256 "de002320ff03b02c9add69c8cf00a1bd67abee36385c35a617b11d14ac7f7c5f"

      define_method(:install) do
        bin.install "kvirtbp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/phenixblue/kvirtbp/releases/download/v0.1.0-rc3/kvirtbp_0.1.0-rc3_darwin_arm64.tar.gz"
      sha256 "6e3367dc9259c789a4b39f9afc02f0c694a93675ad7bbf788a30b7704131bbe8"

      define_method(:install) do
        bin.install "kvirtbp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/phenixblue/kvirtbp/releases/download/v0.1.0-rc3/kvirtbp_0.1.0-rc3_linux_amd64.tar.gz"
      sha256 "422bcbe16fa515e3259655ad0fa618b6b2313623df72fad19b896bf1120c8d1c"
      define_method(:install) do
        bin.install "kvirtbp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/phenixblue/kvirtbp/releases/download/v0.1.0-rc3/kvirtbp_0.1.0-rc3_linux_arm64.tar.gz"
      sha256 "88f670b3c4255dcb48630a7e6476c1edc281881b38adeeef9c51ddec93fa1cba"
      define_method(:install) do
        bin.install "kvirtbp"
      end
    end
  end

  test do
    system "#{bin}/kvirtbp", "version"
  end
end
