# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kvirtbp < Formula
  desc "KubeVirt best-practices scanner for production readiness, security, and availability checks"
  homepage "https://github.com/phenixblue/kvirtbp"
  version "0.1.0-rc4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/phenixblue/kvirtbp/releases/download/v0.1.0-rc4/kvirtbp_0.1.0-rc4_darwin_amd64.tar.gz"
      sha256 "9c7729fc8db144ef946aa85c5aff73784c254dee5f165518e110f66f24ad69ce"

      define_method(:install) do
        bin.install "kvirtbp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/phenixblue/kvirtbp/releases/download/v0.1.0-rc4/kvirtbp_0.1.0-rc4_darwin_arm64.tar.gz"
      sha256 "c5f93f04e4201a4bb0c4d3db70dcb9de08980a0ec98dcc06512ccd10d8050185"

      define_method(:install) do
        bin.install "kvirtbp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/phenixblue/kvirtbp/releases/download/v0.1.0-rc4/kvirtbp_0.1.0-rc4_linux_amd64.tar.gz"
      sha256 "9f2c30adbaff86e716b342558ae26902d9f905d73e45b7eddd64c96e93981d6b"
      define_method(:install) do
        bin.install "kvirtbp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/phenixblue/kvirtbp/releases/download/v0.1.0-rc4/kvirtbp_0.1.0-rc4_linux_arm64.tar.gz"
      sha256 "a30b5ebcb09b6d8c134854c7138aa93f471b0e4cb435356a986a1d4246aca19c"
      define_method(:install) do
        bin.install "kvirtbp"
      end
    end
  end

  test do
    system "#{bin}/kvirtbp", "version"
  end
end
