# This file was generated by GoReleaser. DO NOT EDIT.
cask "k8shark@rc" do
  version "1.0.1-rc.1"

  on_macos do
    on_intel do
      sha256 "99492ac66a090c2f36567804578520ea378d9e25e7825d4606c2f29d2f0b3344"
      url "https://github.com/phenixblue/k8shark/releases/download/v#{version}/k8shark_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "769cb7795828ef0393fe4812f72149f071ccf9874059c4e3026ec06c5ea96b99"
      url "https://github.com/phenixblue/k8shark/releases/download/v#{version}/k8shark_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "cb730af8ec8af2803a683de3ef30c03d290ddc1aacc7da3170a4bb6c606dc190"
      url "https://github.com/phenixblue/k8shark/releases/download/v#{version}/k8shark_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3132440527731c89de2eff8402727a537151a0c1430f3c6c36b88ea5c40cdfea"
      url "https://github.com/phenixblue/k8shark/releases/download/v#{version}/k8shark_#{version}_linux_arm64.tar.gz"
    end
  end

  name "k8shark@rc"
  desc "Kubernetes cluster state capture and mock API replay tool (prerelease channel)"
  homepage "https://github.com/phenixblue/k8shark"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kshrk"

  # No zap stanza required

end
