# This file was generated by GoReleaser. DO NOT EDIT.
cask "k8shark" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "f6fa2b4c40a33bbfff6577b905cb75b55a7d0c9cb013644a5aed708c2ab421e4"
      url "https://github.com/phenixblue/k8shark/releases/download/v#{version}/k8shark_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5043f10596899fbac82ba1ccb1de64989b44fc288f0dd33dc1bd741a579f8871"
      url "https://github.com/phenixblue/k8shark/releases/download/v#{version}/k8shark_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f7149fa083cdfdf0d4d04d9e60aadcf684e0c7b84dfbf75943db812f731074d0"
      url "https://github.com/phenixblue/k8shark/releases/download/v#{version}/k8shark_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c87f02ab8badc3620370debe8e304c83ee598b4f3e6d0519f9946189de4ecf25"
      url "https://github.com/phenixblue/k8shark/releases/download/v#{version}/k8shark_#{version}_linux_arm64.tar.gz"
    end
  end

  name "k8shark"
  desc "Kubernetes cluster state capture and mock API replay tool"
  homepage "https://github.com/phenixblue/k8shark"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kshrk"

  # No zap stanza required

end
