# This file was generated by GoReleaser. DO NOT EDIT.
cask "k8shark@rc" do
  version "1.0.0-rc.1"

  on_macos do
    on_intel do
      sha256 "cf2805110289c46b682277a30c90d0ad20f01ac6daca7888d645cc8812eb687d"
      url "https://github.com/phenixblue/k8shark/releases/download/v#{version}/k8shark_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "098500c0bc3ea7fe00dc6ef9939f1d3dc05eaaf3e3f2f1e551012bda5c4eedba"
      url "https://github.com/phenixblue/k8shark/releases/download/v#{version}/k8shark_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "800ad7f48ec5fdb20a7fe9c97e2bfc31457e12f5ab11c56ba1ed70f70c7d4289"
      url "https://github.com/phenixblue/k8shark/releases/download/v#{version}/k8shark_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "965d40b04a67e2cf4a46270b2cfaa8ab97f3e14960e6c22beaf6c26ec0eb2beb"
      url "https://github.com/phenixblue/k8shark/releases/download/v#{version}/k8shark_#{version}_linux_arm64.tar.gz"
    end
  end

  name "k8shark@rc"
  desc "Kubernetes cluster state capture and mock API replay tool (prerelease channel)"
  homepage "https://github.com/phenixblue/k8shark"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kshrk"

  # No zap stanza required

end
