# This file was generated by GoReleaser. DO NOT EDIT.
cask "k8shark@rc" do
  version "1.0.0-rc.3"

  on_macos do
    on_intel do
      sha256 "7769101e54a59f491321293b34b0081bbbaf58a8662c89225ef5b641b7c73169"
      url "https://github.com/phenixblue/k8shark/releases/download/v#{version}/k8shark_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "05d671a67bff0255ff46e2d770c77d38633aaa9496d938118d02facefb93ed89"
      url "https://github.com/phenixblue/k8shark/releases/download/v#{version}/k8shark_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "408626bea5b2e90095581a60db6294f6c42bbb76eef22fbed9d979ca06d45a86"
      url "https://github.com/phenixblue/k8shark/releases/download/v#{version}/k8shark_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5c34618b8c4030f56d5bfc592cb47afc2136d4784297c114a698dc48284e909f"
      url "https://github.com/phenixblue/k8shark/releases/download/v#{version}/k8shark_#{version}_linux_arm64.tar.gz"
    end
  end

  name "k8shark@rc"
  desc "Kubernetes cluster state capture and mock API replay tool (prerelease channel)"
  homepage "https://github.com/phenixblue/k8shark"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kshrk"

  # No zap stanza required

end
